### ISSUE TITLE
Migration Analytics - Select basic vs. detailed inventory data

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#1005]
Mockup for basic: 
![single page form  - 20190717-single page form - providers - basic data](https://user-images.githubusercontent.com/22823035/61481215-a82fb280-a965-11e9-9f73-9bca67dd683e.png)
Mockup for detailed:
![single page form  - 20190717-single page form - providers - detailed data](https://user-images.githubusercontent.com/22823035/61481230-b4b40b00-a965-11e9-87e6-c9cf001f7d33.png)

**Comment by mturley** [comment]
This will be closed by https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/4
