### ISSUE TITLE
Warm Migration - Change scheduling for Not Started plans 

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#1023]
Change the scheduling options in the Not Started plans list view to replace the separate Migrate and Schedule buttons with a single Schedule Migration button that opens the updated scheduling modal. See #956.

**Comment by vconzola** [comment]
@mturley Did we do this as part of warm migration?

**Comment by mturley** [comment]
@vconzola yes, this was part of the unreleased changes for warm migration.
