### ISSUE TITLE
Migration Status messages need to be updated to match the new ones in the backend

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#1054]
The UI keeps a list of strings that can be present in various properties for migration status. Since these messages are changing in 5.11.1, the UI strings need to be updated so translations will remain correct.

The list of messages in the UI is here: https://github.com/ManageIQ/manageiq-v2v/blob/master/app/javascript/react/screens/App/Plan/PlanConstants.js#L22

The list of messages in the backend is here: https://github.com/ManageIQ/manageiq/blob/master/app/models/infra_conversion_job.rb#L76-L128

Related to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1759062

**Comment by mturley** [comment]
Note: after a brief chat with @mzazrivec about this, it sounds like the better solution would be to have these messages translated on the backend before the UI loads them, so the UI can just display them as-is. That sounds like an ideal way to resolve this to me :)

**Comment by vconzola** [comment]
Resolved in PR #1076. Close.
