### ISSUE TITLE
Migration Schedule later / Retry now inconsistency

### ISSUE THREAD

**Issue by mzazrivec** [ManageIQ/manageiq-v2v#1068]
I'm not entirely sure if it's a feature or a bug / inconsistency, but I'd rather file this to be sure.

There is an inconsistency in behavior of re-scheduling a failed migration plan: if you reschedule the plan immediately (`Retry` button), the plan in question immediately lands in the in progress tab:
![schedule-now](https://user-images.githubusercontent.com/6648365/69242184-99ba0780-0ba0-11ea-8e16-c353e4ec4be6.png)

Though if you specify a date in the future (via the schedule modal), the plan stays in the tab for completed plans and once it is picked up by the queue worker, a in progress status will be rendered next to it:
![migration-later](https://user-images.githubusercontent.com/6648365/69242264-c53cf200-0ba0-11ea-94ca-9acd729f6892.png)

Though even when it's in progress, the plan is still being rendered in the completed tab.

**Comment by vconzola** [comment]
Working as designed.
