### ISSUE TITLE
[BZ#1775998] Inaccurate message is displayed in "Conversion Hosts" page while there is only one provider

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#1072]
https://bugzilla.redhat.com/show_bug.cgi?id=1775998

```
Description of problem:
The "Missing Providers" message displayed is not accurate, in case of VMware -> RHV migration

Version-Release number of selected component (if applicable):
5.11.1.0

How reproducible:
100%

Steps to Reproduce:
Using fresh CFME:
1. Add RHV provider
2. Go to "Migration Settings" -> "Conversion Hosts"

Actual results:
Can't  add conversion hosts due missing providers:
"There are no providers available from which to configure a conversion host. You must configure a target provider before configuring conversion hosts"

Once adding VMware provider -> there is the option to set RHV conversion hosts

Expected results:
The message should be that there is no Source provider
OR to allow to set conversion host while only the RHV provider is configured.
```

It looks like the issue here is that for the conversion hosts page we reuse the "has sufficient providers" check we already had on plans/mappings pages, which checks that you have both VMWare and one of either RHV or OSP.

@vconzola from a UX perspective, which fix would you prefer?
* Change the message so it also mentions configuring a source provider
* Change the behavior so you don't need a VMware provider to get to the conversion hosts page

**Comment by mturley** [comment]
@vconzola do you remember if we decided to change the messaging here or change the behavior?

**Comment by vconzola** [comment]
@mturley Sorry this fell thru the cracks. Seems like changing the behavior is the way to go. If user has a RHV provider configured and doesn't need a VMware provider there's no reason to alert them to an issue that doesn't exist.

**Comment by mturley** [comment]
Ok, sounds good. Will see if I can get this into my batch of changes for Monday.
