### ISSUE TITLE
FormField: Info popover appears twice if `inline_label` is true

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#1084]
@mzazrivec , I found a bug in the FormField component that I missed when reviewing https://github.com/ManageIQ/manageiq-v2v/pull/1075. It's caused by this change: https://github.com/ManageIQ/manageiq-v2v/commit/aab6fa0bc190c2adf3f4a21136c697580a2d067f#diff-ad25e29f326cc9bdfc3075193546532aR105-R110

I noticed on the Configure Conversion Host wizard that if you use the default behavior of `inline_label: true`, the info popover renders in two different places for each field:

<img width="911" alt="Screenshot 2020-01-09 17 14 21" src="https://user-images.githubusercontent.com/811963/72109540-11382780-3304-11ea-9854-794b2089ad4d.png">

This is only present on master and won't be an issue on ivanchuk until we backport https://github.com/ManageIQ/manageiq-v2v/pull/1075.

**Comment by mzazrivec** [comment]
@mturley Yep, I can see the problem as well. Though before I make the thing even worse, I better ask: what is the semantics of `inline_label` parameter of the `FormField` component?

**Comment by mturley** [comment]
@mzazrivec it looks like you added the `inline_label` prop in https://github.com/ManageIQ/manageiq-v2v/commit/208fd3040ff1de446bd045a6f530055cc766d5b3#diff-ad25e29f326cc9bdfc3075193546532aR23 😄  I think when it's true it's supposed to use the (old) default behavior of putting the label in its own column, and when false it instead renders the label above the field in the same column.

It looks like `renderInfoPopover()` was part of this original label snippet that is hidden when `inline_label` is false, but in that commit it wasn't added to the label rendered above the field when `inline_label` is true. Later `renderInfoPopover()` was added after that line, but not behind a condition, so it's rendering twice when `inline_label` is true. I think we just need to put it behind that `!inline_label` condition.

So something like this, except maybe inside the same div as the label instead of in a fragment, not sure which would look right.

```diff
--- a/app/javascript/react/screens/App/common/forms/FormField.js
+++ b/app/javascript/react/screens/App/common/forms/FormField.js
@@ -106,8 +106,12 @@ export const FormField = ({
         </Grid.Col>
       )}
       <Grid.Col sm={Number.parseInt(controlWidth, 10) || 9} id={input.name}>
-        {!inline_label && <div style={{ fontSize: '15px', display: 'inline' }}>{label}</div>}
-        {renderInfoPopover()}
+        {!inline_label && (
+          <React.Fragment>
+            <div style={{ fontSize: '15px', display: 'inline' }}>{label}</div>
+            {renderInfoPopover()}
+          </React.Fragment>
+        )}
         {renderField()}
         {(help || (touched && error) || warning) && (
           <Form.HelpBlock>
```

**Comment by mzazrivec** [comment]
@mturley Well I'll be ... Yes, it was originally my code. Thanks.

Fixing PR: https://github.com/ManageIQ/manageiq-v2v/pull/1088
