### ISSUE TITLE
UI gets blank when click next for "Authentication" while configuring OSP conversion host 

### ISSUE THREAD

**Issue by mnadeem92** [ManageIQ/manageiq-v2v#1093]
I find issue with conversion host wizard UI while configuring OSP conversion host, the same works fine for RHV conversion host.

Steps To Reproduce:
**********************************
1. launch the conv. host wizard
2. Fill "Location" page for openstack base environment 
3. in next step, select an instance/VM in "Hosts" page
4. hit next
5. you will get a blank page

**Comment by mnadeem92** [comment]
![conver-host-conf-blankpage](https://user-images.githubusercontent.com/42543378/72711535-3abc4300-3b8f-11ea-9455-e1f2d5724241.png)
![conv-host-conf1](https://user-images.githubusercontent.com/42543378/72711536-3abc4300-3b8f-11ea-8752-81be368c3bba.png)

**Comment by mnadeem92** [comment]
The issue is with GUI only, API works perfectly fine.

**Comment by mturley** [comment]
This is happening as a result of https://github.com/ManageIQ/manageiq-v2v/issues/1089. @mnadeem92 , what version of ManageIQ/CloudForms were you using when you found this? I was hoping it was still only happening on master.

**Comment by mnadeem92** [comment]
> This is happening as a result of #1089. @mnadeem92 , what version of ManageIQ/CloudForms were you using when you found this? I was hoping it was still only happening on master.

I have reproduce it on ManageIQ Jansa Version master.20200118225846_b8aaf77

**Comment by mturley** [comment]
Ok, that's good. I need to make sure it's not happening on the latest Ivanchuk build, but I can follow up on that later.

**Comment by mturley** [comment]
Closed in #1102
