### ISSUE TITLE
The MappingWizard has a WarningModal that is redundant with the abstracted ConfirmModal

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#145]
We should refactor away the reduntant code from `App/Overview/screens/MappingWizard/components/WarningModal/WarningModal.js` that can be replaced with a usage of the new `ConfirmModal` (currently at `App/common/ConfirmModal.js`, but being moved into `patternfly-react` soon).

See comments on #132 from myself and @michaelkro.

**Comment by mturley** [comment]
This is now being rolled into my next PR.

**Comment by mturley** [comment]
Closed by #132

**Comment by mturley** [comment]
Oh oops, no it wasn't closed by #132. My mistake. This abstraction still needs to be made uniform everywhere

**Comment by mturley** [comment]
Sorry I haven't gotten to this yet @priley86 . Haven't forgotten about it.

**Comment by priley86** [comment]
I think @michaelkro is grabbing this! He started a contribution into pf-R...so we should be in good shape soon...
https://github.com/patternfly/patternfly-react/pull/363

**Comment by mturley** [comment]
Awesome! Beat me to it. All good stuff.

**Comment by serenamarie125** [comment]
We should be using the new PF React component, when ready: https://github.com/patternfly/patternfly-react/pull/363

**Comment by mturley** [comment]
We should use the `MessageDialog` component here as Serena mentioned a while back :)

**Comment by mturley** [comment]
Still should be done, but very low priority.

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.
