### ISSUE TITLE
Integrate Redux store / reducers w/ mIQ Core

### ISSUE THREAD

**Issue by priley86** [ManageIQ/manageiq-v2v#17]
In this issue we will ensure that all reducers are registered correctly via `ManageIQ.redux.addReducer` and that the store is also registered correctly via `ManageIQ.redux.store`. 

cc: @vojtechszocs @ohadlevy

I will follow up with you soon in talk.manageiq.org or in Gitter.

**Comment by priley86** [comment]
@ohadlevy @vojtechszocs @himdel  can you provide the latest update on this? Would like to know if we should try to address it this upcoming sprint.

**Comment by himdel** [comment]
@priley86 I think there's nothing stopping you from doing this now, yeah :)

**Comment by michaelkro** [comment]
closed by #533
