### ISSUE TITLE
Timeout while in Pending State

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#228]
If a migration execution does not go from pending to active state we need to timeout the execution and alert the user.
- Display a persistent toast notification telling the user the plan timed out and try the migration again later.
- Provide an action link in the toast to cancel the execution.
- Remove the pending in progress card and return the plan to not started state.

Based on email discussion (April 16-17) with Bill W. and others, we should defer this until post Summit.

**Comment by serenamarie125** [comment]
@vconzola 

1. !here will "Timed Out" plans be shown (before they are canceled) ?  In Progress?
2. can you retry a timed out plan?  Or only cancel it?
3. can we provide exact text for the toast? what will the link text be "Cancel Plan?"
4. is there a Cancel action the card as well ?

**Comment by vconzola** [comment]
@serenamarie I just wanted to open this issue so we didn't lose it. I will work on the detailed design post  Summit.
