### ISSUE TITLE
Infra Mapping plan cannot be edit, after creation.

### ISSUE THREAD

**Issue by istein1** [ManageIQ/manageiq-v2v#250]
Once the Mapping plan is created is not editable.

Version-Release:
master.20180417121918_2dd64f8 

Expected results:
It should be possible to edit Infra mapping plan.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1571770

**Comment by vconzola** [comment]
@istein1 Ability to edit/delete mappings and plans are on the roadmap for post-Summit sprints.

**Comment by istein1** [comment]
Glad to hear, thanks or the update.

**Comment by vconzola** [comment]
Duplicate of #607. Has been resolved by PR #620.
