### ISSUE TITLE
Migration completed notifications should also appear on detail screen

### ISSUE THREAD

**Issue by priley86** [ManageIQ/manageiq-v2v#265]
* to fix this, we can bubble up the `_getTransformationPlansActionCreator` redux call a level in the hierarchy (so that polling occurs for that request on both Overview and Overview Detail).

I'm fine w/ deferring this for now...

**Comment by mturley** [comment]
Starting on this tomorrow, unless @AparnaKarve can use my help in finishing the Redux part of #511.

**Comment by mturley** [comment]
Talked to @AparnaKarve, she is working on higher priority things but she had already started this one. Starting on #240 instead.

**Comment by michaelkro** [comment]
@priley86 @AparnaKarve 

It was my impression that this issue concerned showing alerts of migration plans completing, as opposed to individual migration tasks.

e.g., you could be viewing the details page for `migration plan 1` and when `migration plan 2` completes/fails, the notification would appear.

**Comment by vconzola** [comment]
@michaelkro that was my belief too. i don't think we show notifications when individual tasks complete; only when a plan (request) completes. although...that might be a nice feature to add, just not in this PR.

**Comment by AparnaKarve** [comment]
Somehow it made sense to me to display notifications for individual tasks especially since we are in the Plan Detail page. 

> you could be viewing the details page for migration plan 1 and when migration plan 2 completes/fails, the notification would appear.

This is also a good addition and I can look into that in a separate PR.

**Comment by michaelkro** [comment]
ok, awesome!

**Comment by AparnaKarve** [comment]
> you could be viewing the details page for migration plan 1 and when migration plan 2 completes/fails, the notification would appear.

@michaelkro I am planning on working on this next, although, this would involve bigger changes which I think should not go in gaprindashvili, just to be on the safer side.

**Comment by michaelkro** [comment]
definitely agree @AparnaKarve.  I also anticipate that to be a considerable effort and possibly an opportunity to streamline our polling.

We should create a separate issue for that, or create one for #543 and keep this one open.  Whichever you prefer

**Comment by AparnaKarve** [comment]
Re-opening this issue since the part mentioned in https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/265#issuecomment-410844130 is still pending

**Comment by AparnaKarve** [comment]
It seems more efficient to add this notification from the backend.
currently looking into implementing this via the backend automate code.
