### ISSUE TITLE
The spinner2 icon in the Plan page breadcrumb bar (plan "in progress" state) should be an animated Spinner component and not a static icon.

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#406]
Sorry @vconzola, you said we should wait for someone to complain, but it's bothering me so I guess I'm the complainer. Low-low-low priority.

I tried dropping in a `<Spinner />` instead of the `<Icon ... />` but it didn't render. Silently disappeared. So I didn't waste time on it. But the spinner2 icon is just a weird little sort of... sideways refresh button that isn't clickable? I'm not happy on where I landed with that, which was due to a miscommunication between me and @vconzola in handling https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/347

**Comment by priley86** [comment]
Related to https://github.com/ManageIQ/manageiq-v2v/issues/204

**Comment by mturley** [comment]
This is still a thing, we should get to it eventually. See you again in 6 months, miq-bot.

**Comment by vconzola** [comment]
LOL! I get these all the time. Do you just need to comment in them to keep
them alive?

VINCE CONZOLA

SR. INTERACTION DESIGNER, USER EXPERIENCE DESIGN

Red Hat <https://www.redhat.com/>

vconzola@redhat.com    T: 9197165041
<https://red.ht/sig>

**Comment by mturley** [comment]
I think so, yeah. I removed the `stale` label myself but I think the bot will remove it for you if you comment. Any activity should keep it alive, like changing labels, if we wanted to use those to kick something down the road.
