### ISSUE TITLE
Enhancement - Ability to filter VMs from VMware folders

### ISSUE THREAD

**Issue by mberube99** [ManageIQ/manageiq-v2v#429]
When selecting VMs in a migration plan, the user would like the ability to filter VMs by VMware folder as folders are often used to group VMs related with each other.

**Comment by mberube99** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1593839

**Comment by mturley** [comment]
This was duplicated in https://github.com/ManageIQ/manageiq-v2v/issues/914 and should have been closed in https://github.com/ManageIQ/manageiq-v2v/pull/917.
