### ISSUE TITLE
Reduced downtime migrations (warm migrations)

### ISSUE THREAD

**Issue by mberube99** [ManageIQ/manageiq-v2v#433]
Migration plans should offer 2 migration options:

-  Cold migration :  Faster but requires downtime during the full migration process
-  Warm migration:  Slower as data is copied while the VM is running and the VM is only rebooted at the end of the migration process.

[ This feature is currently scheduled for IMS 1.2 only ]

**Comment by mturley** [comment]
Using this as the umbrella issue for warm migration, will close when all related PRs are merged.
