### ISSUE TITLE
Ability to group VMs and define dependencies inside a migration plan

### ISSUE THREAD

**Issue by mberube99** [ManageIQ/manageiq-v2v#434]
When creating a migration plan, I would like the ability to define VM groups from my full list of VMs to be migrated, and define dependencies between those groups.

Example:  
   Group 1 = web1, app1, db1;  
   Group 2 = web2, app2, db2;  
   migration rule : Group 2 only gets migrated once group 1 has been fully migrated;

[ This feature is currently schedule for IMS 1.2 only ]

**Comment by bthurber** [comment]
@vconzola we are tracking this for IMS 1.1.  Checking status.
