### ISSUE TITLE
Remove migration plans from Service Catalog Items

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/manageiq-v2v#435]
Description of problem:
When creating migration plans in the Migration plugin, they also appear under Services > Catalogs > Catalog Items.

Version-Release number of selected component (if applicable):
5.9.3 and latest MiQ nightly

How reproducible:
Everytime

Steps to Reproduce:
1. In Migration plugin, create a migration plan
2. Navigate to Services > Catalogs > Catalog Items
3. Migration plans are listed 

Actual results:
Migration plans are listed under:  Services > Catalogs > Catalog Items

Expected results:
Migration plans do not appear in the Service Catalog

**Comment by priley86** [comment]
is this a backend issue? Or do we need to specify some additional attribute? Forgot to ask about this yesterday...

**Comment by AllenBW** [comment]
@ManageIQ/core hi friends 👋 yer friendly neighborhood v2v ui team needs help here pretty please

**Comment by gmcculloug** [comment]
This is being tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1594408

I have talked to @dclarizio about it yesterday and I think we just need to filter out the Migration plans when requesting the list of Service Template objects.  This is the first Service Template sub-class that we want to remove.

Waiting for @h-kataria to return from PTO next week so we can address.

**Comment by AllenBW** [comment]
Thanks for the update on this @gmcculloug 🙇‍♀️ 🍭 🤗
