### ISSUE TITLE
Infra mapping list view / plan list view design

### ISSUE THREAD

**Issue by priley86** [ManageIQ/manageiq-v2v#504]
Revisit designs related to list view content / flexed content / custom styled content. We will likely need a PF Designer to weigh in and give more targeted feedback. The list view designs often become more complex and require custom styling if there is more content than PatternFly expects.

Noted initially in #500

**Comment by mturley** [comment]
Partially addressed in https://github.com/ManageIQ/manageiq-v2v/pull/934 which fixed the alignment of the items in the plans list view. Closing as wontfix for the rest, we may address this at a later date.
