### ISSUE TITLE
Display a message to the user if a scheduled migration plan fails to run and allow the user to reschedule the plan

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#520]

**Comment by mturley** [comment]
@vconzola tells me that @AllenBW ran into this when first implementing the schedule feature, saying that a migration could somehow reach its scheduled time but be stuck in an orphaned state where it's not running and it can't be cancelled or rescheduled.

@AllenBW I know this is quite a dusty one... can you recall at all what the details are here?

**Comment by mturley** [comment]
Closing as `wontfix`.
