### ISSUE TITLE
Abstract reducer logic into helper functions

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-v2v#536]
[Reducers have gotten bloated](https://github.com/ManageIQ/miq_v2v_ui_plugin/blob/11e649cfd158211e1163310a73f8a58cf45f577b/app/javascript/react/screens/App/Plan/PlanReducer.js), its no ones fault.  It would be nice to clean these up a bit by abstracting much of the bloat into a local `helper.js`

https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/526#issuecomment-410278123

**Comment by mturley** [comment]
It's no one's fault, but it's a little my fault.

**Comment by AllenBW** [comment]
And a little my fault.
