### ISSUE TITLE
OSP Support: Add a new step to the Plans wizard when migrating to OpenStack

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#546]
If the infrastructure mapping selected in step 1 of the Plans wizard has OpenStack as a target, then after VM selection add a step to the wizard for instance properties.
![9cccc3-createplan-vms-selection osp option4](https://user-images.githubusercontent.com/22823035/43740094-45434aa2-9998-11e8-9d80-43da64beafa8.png)

![screenshot 2018-08-14 11 17 13](https://user-images.githubusercontent.com/811963/44100713-a3d820e4-9fb3-11e8-9edd-2a0553486baf.png)

**Comment by mturley** [comment]
This issue tracks the entire Instance Properties step, which has been worked on in the following PRs so far:

https://github.com/ManageIQ/manageiq-v2v/pull/547
https://github.com/ManageIQ/manageiq-v2v/pull/562
https://github.com/ManageIQ/manageiq-v2v/pull/627

we still need to alter the POST body when submitting the new plan to the API to include these selections.

**Comment by michaelkro** [comment]
We can close this issue right?

**Comment by mturley** [comment]
Yeah, thanks for following up. This one's been done for a while.
