### ISSUE TITLE
Progress bar does not update for migrations performed via SSH Transformation Method

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#556]
https://bugzilla.redhat.com/show_bug.cgi?id=1613919

Progress bar does not update for migrations performed via SSH Transformation Method, neither updates on Migration Dashboard, nor on Migration Request Details Page. Progress bar updates only once, at the very end of migration. It goes from 0 % to 100% directly in one shot.

**Comment by AparnaKarve** [comment]
Confirmed that this is a backend issue.

The `percent` value under `virtv2v_disks` always stays at 0 when transformation method is `ssh`

```
"virtv2v_disks": [
  {
    "path": "[NFS_Datastore_1] v2v-win2016/v2v-win2016.vmdk",
    "size": 42949672960,
    "percent": 0,
    "weight": 100.0
  }
],
```

**Comment by vconzola** [comment]
Closing issue.

Per Fabien: The problem is in virt-v2v-wrapper, so oVirt product.
Closing this BZ in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1614748.
