### ISSUE TITLE
[OSP] Update Overview Infra Mapping List

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#572]
The infra mapping ListView needs to be updated to be compatible with OSP mappings

**Comment by vconzola** [comment]
The gist of this one is that the way mappings are visualized in the list view expansion today is very RHV centric and needs to be updated for OSP.

**Comment by mturley** [comment]
It looks like this is all we'll need for this one, but `cloudvolume` will need to be replaced with `cloudvolumetype` eventually: https://github.com/ManageIQ/manageiq-v2v/compare/master...mturley:572-osp-infra-mapping-list

**Comment by vconzola** [comment]
@mturley This is just a labeling thing. When OSP mappings are expanded they should look like this (ignore the contents of the boxes, just look at the labels):
![netowk slice](https://user-images.githubusercontent.com/22823035/46377037-96468280-c665-11e8-9273-3ad48a90171f.png)
![dtaastore slice](https://user-images.githubusercontent.com/22823035/46377048-9d6d9080-c665-11e8-8bde-37c0050edb8a.png)
![osp project mapping](https://user-images.githubusercontent.com/22823035/46377057-a1011780-c665-11e8-9590-e61f63b931e3.png)
