### ISSUE TITLE
[UI CLEANUP] Connect <Migrations /> and lift redux state from <Overview />

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#573]
We are mapping state to props in `Overview` that could be done further down the component tree

The following could be moved from `<Overview />` to `<Migrations />`.  Please note that this may not be a comprehensive list, and that the props should be verified before lifting.

1. `serviceTemplatePlaybooks`
2. `allArchivedPlanRequestsWithTasks`
3. `toggleScheduleMigrationModal`
4. `scheduleMigrationModal`
5. `scheduleMigrationPlan`
6. `scheduleMigration`
7. `archiveTransformationPlanUrl`
8. `archiveTransformationPlanAction`

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.
