### ISSUE TITLE
Non operational "Retry" button in Mapping Wizard

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#577]
# Steps to Reproduce
- Currently, there is a bug that allows the user to progress past the first step of the Mapping Wizard after entering a duplicate name (please see issue #576) 
- At the end of the wizard, attempting to create a mapping with a duplicate name results with the error state shown in the screenshot below
- There is no action bound to the `Retry` button

# Screens
<img width="1440" alt="fullscreen_8_15_18__8_58_am" src="https://user-images.githubusercontent.com/15141412/44149307-a5846cfc-a069-11e8-8b6a-18b089a3523a.png">

**Comment by AllenBW** [comment]
@vconzola Whats the desired fix here? surely prevent progress with invalid form, but also, do we want to remove the retry button? or send em back to step one?

**Comment by vconzola** [comment]
@allenbw if we fix #576 the user will never get to the error or the Retry button, right? so i'm not sure we need to address the issue raised here. unless we're trying to address the general case where creating the mapping fails for any reason? in that case Retry should take the user back to wizard step 1.

I'm guessing we don't get any meaningful error information explaining the failure, right?

**Comment by AllenBW** [comment]
@vconzola When/if something goes wrong, we'll see the above, an api error notification and then the error page of the wizard... So, confirmation, retry goes back to step 1?

**Comment by vconzola** [comment]
@AllenBW  Yes. If we can't give the user any more meaningful information about the error, let's just send them back to the beginning. Not great UX, but it sounds like it's the best we can do.
