### ISSUE TITLE
UI: Text should be wrapped in popover properly

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/manageiq-v2v#579]
**Description**
This is UI issue. Popover should adjust its width if text length is greater than its size.
Text should be wrapped in popover properly. 

In above image while displaying hostname, `.com` is displaying outside of popover so it should be wrapper inside.

**Version**
5.9.4.4.20180816162527_c00eb23 

**Impact**
None

![screenshot from 2018-08-17 15-03-29](https://user-images.githubusercontent.com/10824880/44259817-4421dd00-a230-11e8-89c0-a2323194856a.png)

**Comment by AllenBW** [comment]
<img width="1217" alt="screen shot 2018-08-17 at 9 18 57 am" src="https://user-images.githubusercontent.com/6640236/44268155-9ba75500-a1fe-11e8-9deb-263acd124df1.png">


yeah sort of a general issue with pfr popovers, really long strings (with no breaks) cause overflow
