### ISSUE TITLE
Red Cross Symbol in front of Plan Name for Plan that is not even started

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#594]
https://bugzilla.redhat.com/show_bug.cgi?id=1618844

Needs to be verified as a real bug. Hold off on this one for a bit. Track status of BZ.

**Comment by michaelkro** [comment]
Bug confirmed.  Looking into finding cause

# Screens
<img width="1152" alt="fullscreen_8_21_18__9_14_am" src="https://user-images.githubusercontent.com/15141412/44403553-ca853a00-a522-11e8-9ae7-d6daa984cbb2.png">
