### ISSUE TITLE
Configure Providers screen is visible with the Create Migration Plan button

### ISSUE THREAD

**Issue by AparnaKarve** [ManageIQ/manageiq-v2v#600]
I just noticed this -
<img width="1432" alt="screen shot 2018-08-21 at 12 05 52 pm" src="https://user-images.githubusercontent.com/1538216/44423373-d7ae2300-a53a-11e8-8a2a-0c4eb381c600.png">

We should not be displaying the Create Migration Plan button/links when there are no providers

**Comment by vconzola** [comment]
Also, I'm not sure how/why we're showing the Migration Plan empty state when there are no Infrastructure Mappings. If there are no mappings we should always be showing the mappings empty state.

**Comment by mturley** [comment]
@AparnaKarve I just tried to reproduce this and couldn't. Deleting all my plans and mappings, I just get the Create Infrastructure Mapping empty state as expected. Can you still reproduce it?

**Comment by AparnaKarve** [comment]
@mturley Looks like this was fixed by https://github.com/ManageIQ/manageiq-v2v/pull/616.

Closing the issue...
Thanks for checking.
