### ISSUE TITLE
Edit an existing Migration Plan

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#607]
![screen shot 2018-08-29 at 3 39 24 pm](https://user-images.githubusercontent.com/22823035/44811118-c6e85780-aba1-11e8-80d9-b355a98ca3ab.png)
Notes:
- Only plans in Not Started state can be edited. (What about Complete - Failed state?)
- Edit action is located in a kebab menu.
- Selecting Edit opens the Migration Plan Wizard with saved values pre-filled for all fields on all steps.

**Comment by mturley** [comment]
I'm starting to look at this next.

**Comment by vconzola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for editing infrastructure mappings and migration plans](https://trello.com/c/xGHQDIny/198-support-for-editing-infrastructure-mappings-and-migration-plans)
