### ISSUE TITLE
Create a separate Infrastructure Mappings page available from Migration in the nav

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#609]
![infrastructure mappings page](https://user-images.githubusercontent.com/22823035/44802480-d52a7980-ab89-11e8-990b-850d15d15877.png)
Notes:

- Infrastructure Mappings will be available as an option under Migration in the CF navigation.
- Page should have breadcrumbs allowing navigation back to Migrate - Overview.
- List view of mappings should be filterable on Name and Description fields and sortable by Name and number of Associated Plans.
- All other behavior is the same as when infra mappings were on the Overview page.

**Comment by vconzola** [comment]
![infrastructure mappings page](https://user-images.githubusercontent.com/22823035/44802480-d52a7980-ab89-11e8-990b-850d15d15877.png)
Notes:

- Infrastructure Mappings will be available as an option under Migration in the CF navigation.
- Edit is only available for mappings with no associated plans.
- Behavior is the same as when infra mappings were on the Overview page.

**Comment by vconzola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove infrastructure mappings from the Overview page](https://trello.com/c/6mFdabrV/201-remove-infrastructure-mappings-from-the-overview-page)

**Comment by michaelkro** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1640275
