### ISSUE TITLE
Show "No clusters found" in the infra mapping wizard if clusters have not been configured

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#611]
In the source and target cluster list boxes in step 2 of the infra mapping wizard, alert the user if either the source or target provider is present but no clusters are found. Currently, we just show an empty list box which leads to user confusion.

**Comment by AllenBW** [comment]
@vconzola The source/target areas are selects, it might be tricky to center the message as is done in the mapping section, (fair warning the message might show up just as there was an option).  UNLESS it is ok to display the message sans dropdown box.

OOO also, the message should be "No cluster found"  also, should we apply this to all of the dropdown select things? when no resource is found, indicate so to the user?

**Comment by vconzola** [comment]
@AllenBW I was thinking something like this. Is this possible? The only user action is to Cancel out of the wizard, but at least we'll give him/her a clue as to the problem.
![screen shot 2018-08-29 at 11 38 42 am](https://user-images.githubusercontent.com/22823035/44798737-4b29e300-ab80-11e8-8480-585d5ce8bdcb.png)
As for datastores and networks, I don't know what's possible in CloudForms. If you can have a cluster configured without datastores or networks, then yes, we should tell the user in the same way - error message in the drop down.

**Comment by AllenBW** [comment]
Righto! Will give it a go 😋
