### ISSUE TITLE
Create a separate Migration Settings page available from Migration in the nav

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#624]
In order to support migration throttling we need a place for users to specify throttling parameters in the IMS UI. This will be done on a new Migration Settings page. It will also serve as a placeholder for future settings.

**Comment by mturley** [comment]
According to @vconzola, this is no longer needed for the short term throttling solution:

> just heard in the v2v scrum that since they still haven't settled on a long term backend solution for throttling for now Fabien is going to do it all it automate and there is no need for user input. So that means for the time being we will need to not expose the Migration Settings page in the UI. So don't merge any of the code you've been working on for that into Master.

When we do want to bring this page in, we can start with my branch here: https://github.com/ManageIQ/manageiq-v2v/compare/master...mturley:migration-settings-page

![k5s2ew0g0s](https://user-images.githubusercontent.com/811963/45693732-bb96a500-bb2b-11e8-9e1f-3df29c6d3755.gif)

**Comment by michaelkro** [comment]
Do we want to close this one out now that https://github.com/ManageIQ/manageiq-v2v/pull/782 has been merged, and create a new issue for the 1.2 feature?  Or just update this one?

**Comment by vconzola** [comment]
@michaelkro @mturley Let's close this one out and create a new issue for the advanced throttling settings that will be in the z-stream.
