### ISSUE TITLE
Infra mapping name never "loads" in plan list views

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#625]
# Steps to Reproduce
- Have at least one not started or completed migration plan
- Delete all infra mappings
- Notice that the associated mapping name for the plan list item never changes from "Loading Infrastructure Mapping Info..."

# Expected Behavior
After infra mapping fetch completes, the message should read "Infrastructure mapping does not exist"

# Screens
## Current Behavior
<img width="1920" alt="fullscreen_9_4_18__3_41_pm" src="https://user-images.githubusercontent.com/15141412/45053798-1377db00-b059-11e8-8716-d7b647929ddd.png">

## Expected Behavior
<img width="1920" alt="fullscreen_9_4_18__3_45_pm" src="https://user-images.githubusercontent.com/15141412/45053969-94cf6d80-b059-11e8-854e-117506b7ce41.png">

**Comment by AparnaKarve** [comment]
@michaelkro I noticed that the initial status is "Loading Infrastructure Mapping Info...", but later in the subsequent poll, the proper status of the Infrastructure mapping is reflected - either with a name or with "Infrastructure mapping does not exist"

**Comment by michaelkro** [comment]
@AparnaKarve weird, that's not happening for me.  Have you deleted all of your mappings?

**Comment by AparnaKarve** [comment]
@michaelkro Ok, confirmed that if all my mappings are deleted then the Loading message persists forever.
