### ISSUE TITLE
[QEDevCollab] Need unique id for selected position

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/manageiq-v2v#632]
Extended version of https://github.com/ManageIQ/manageiq-v2v/issues/415

We need unique id for following selected div position. 

![screenshot from 2018-09-07 16-38-15](https://user-images.githubusercontent.com/10824880/45216401-1fb0a200-b2be-11e8-83ee-3e405df4910a.png)

Expecting something like this `<div id="progress-bar-items" class="col-xs-12">` to select div items

**Comment by Yadnyawalkya** [comment]
@AllenBW @AparnaKarve  can we have this asap :) :+1:

**Comment by michaelkro** [comment]
@Yadnyawalkya, is this still something that QE would like to have?

**Comment by Yadnyawalkya** [comment]
yes @michaelkro, we are still using temp locators and adding ^^ ids will be helpful.

**Comment by michaelkro** [comment]
@Yadnyawalkya need some clarification.  Do you only need an id for the in progress view?  There is a similar div for each of the migration states (in progress, complete, not started, archived).

**Comment by vconzola** [comment]
Close via #838 .
