### ISSUE TITLE
[INSTANCE PROPERTIES STEP] Warn if chosen flavor may not be big enough

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#644]
***Follow up task for Instance Properties Step***

Warn if the user edits a row in the Instance Properties Step Table to choose a flavor that is not "big enough", i.e., the chosen flavor is neither the `best fit flavor` nor does it exist in the `all fit` collection

**Comment by vconzola** [comment]
Per discussion with @michaelkro if the "all fit" list is empty we will (1) show the flavor with the largest storage as default, (2) not allow any other options in the dropdown, and (3) display a warning icon to the right of the flavor name saying, "None of the existing OpenStack flavors can fit this VM. This might cause migration to fail. We have chosen the flavor with the largest storage size, but you might want to create a new OpenStack flavor that will definitely fit the VM."

**Comment by michaelkro** [comment]
The preferred option is the first shown in [these mocks](https://docs.google.com/presentation/d/1zloqc7El5bL_7sGsW4nE9kM91a9jWY5_fastpkmBhd0/edit#slide=id.p) (custom table header with icon & popover)

**Comment by mturley** [comment]
Per @michaelkro, instead of the flavor with the largest storage:

> Marco wants us to use RAM capacity to determine size.  If it’s a tie, then fall back to number of CPU cores

**Comment by vconzola** [comment]
@mturley Correct. I think what we decided (correct me if I'm wrong @michaelkro ) is that we'll use a reverse Price is Right rule for this - if the back end doesn't return a best fit flavor the UI will choose the flavor that is closest in memory size and larger than the VM. If no flavors are larger than the VM, the best fit will be the one closest to and smaller than the VM. If multiple flavors have the same closest memory size, then choose the flavor with the closest number of CPU cores.

I think this is a temporary solution and long term the back end will always return a best fit. Right?

**Comment by vconzola** [comment]
@michaelkro I thought you had a core PR last week that allows us to get that information now? Refer to this email chain - "v2v UI Question about Flavors".

**Comment by mturley** [comment]
@vconzola, I chatted with Mike about this and he clarified that we don't need to know the VM memory size in this part of the UI code, because in the case where there is a flavor larger than the VM, the back end will always return it as a best fit. So if there's no best fit from the back end, we're already in the "closest to and smaller than the VM" case, which just means the largest flavor available.

End of confusion. 🙃
