### ISSUE TITLE
Change the title of the infrastructure mapping wizard

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#647]
The title of the infrastructure mapping wizard should match the action being performed in the wizard, so it should either be "Create Infrastructure Mapping" or "Edit Infrastructure Mapping".

**Comment by mturley** [comment]
@michaelkro here's a one-liner for this to be cherry-picked onto your branch for #660 : https://github.com/mturley/manageiq-v2v/commit/c32edce5cf8a94c61ef77225019b9576142e767a

**Comment by michaelkro** [comment]
Commit added to #660
