### ISSUE TITLE
Add selected counts to the target object lists in the infrastructure mapping wizard

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#648]
Currently, the number of selected items is only shown below the list of source objects (clusters, datastores, networks) in the infrastructure mapping wizard. The select count should also be shown for the target objects.
![screen shot 2018-09-18 at 10 22 41 am](https://user-images.githubusercontent.com/22823035/45694247-d87fa800-bb2c-11e8-9380-d44ebce30485.png)

**Comment by michaelkro** [comment]
Question:  It is only ever possible to select a single target.  Would adding a counter be confusing?  If I read `1 of 3 selected`, it would make me think I could select `2 of 3`

**Comment by vconzola** [comment]
I'm torn on this one. I understand what Jeremy is saying about it looking funky to have it on one list and not the other, but you also make a good point. Do we prevent the user from selecting more than 1 on the target side? The time I can see it being useful is if there's a long list of targets and you need to scroll, you would know if one is selected that you can no longer see.

**Comment by michaelkro** [comment]
We do indeed prevent multiple selections in the targets list.  I guess we could put a counter down there that is populated with `0 of 1 selected` initially and `1 of 1 selected` when a target is chosen

**Comment by vconzola** [comment]
That's what I was thinking.
