### ISSUE TITLE
UX changes to step 2 of the migration plan wizard

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#650]
1. Change table header to "Select VMs to be Migrated".
2. Increase width of the textbox filter.
~~3. Remove the Search icon - what does it do?~~
4. Increase default number of rows per page to 10.

![screen shot 2018-09-18 at 11 15 41 am](https://user-images.githubusercontent.com/22823035/45697641-3b287200-bb34-11e8-9c48-8ed4c1b89d0a.png)

**Comment by vconzola** [comment]
@mturley  Updated original comment to remove the 3rd issue involving the Search icon. Will open a separate issue if we decide to do this.

**Comment by mturley** [comment]
Thanks @vconzola. Here's a PR for the rest: https://github.com/ManageIQ/manageiq-v2v/pull/682
