### ISSUE TITLE
Migration UI stalls sometimes on appliance reboot

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#665]
See details at: https://bugzilla.redhat.com/show_bug.cgi?id=1631462

**Comment by vconzola** [comment]
@kedark3 We have not seen this. Can you please add more details and/or a screenshot?

**Comment by kedark3** [comment]
@vconzola there is nothing really to add in screenshot here. What really happens is, UI does not detect the migration was complete, and the migration plan keeps showing that plan is in progress, for indefinite long time after the migration is actually completed. So, summary is "It gets stuck in progress".

**Comment by vconzola** [comment]
@kedark3 Is this reproducible or random?

**Comment by kedark3** [comment]
@vconzola its inconsistent.

**Comment by AparnaKarve** [comment]
@kedark3 The next time this happens can you point us to your appliance?
Thanks!!

**Comment by AparnaKarve** [comment]
@kedark3 Do you recall seeing a `VM migrations stalled` status in the Plan detail page for any of the VM tasks?

**Comment by kedark3** [comment]
@AparnaKarve I'll see if I can reproduce. But NO it did NOT say `VM migrations stalled`, it kept showing its `Migrating`

**Comment by michaelkro** [comment]
I think this is a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1639753

If so, this has been resolved by https://github.com/ManageIQ/manageiq-v2v/pull/700

**Comment by kedark3** [comment]
@michaelkro no these are two different issues. I will see if I can reproduce it today.

**Comment by vconzola** [comment]
@michaelkro to follow up with KK and get a screenshot.

**Comment by vconzola** [comment]
BZ is closed. Closing issue.
