### ISSUE TITLE
Network goes Missing in Infra Mapping

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#666]
Two bzs related to this issue : 
https://bugzilla.redhat.com/show_bug.cgi?id=1619431
https://bugzilla.redhat.com/show_bug.cgi?id=1619131

**Comment by agrare** [comment]
Fixed by https://github.com/ManageIQ/manageiq-providers-ovirt/pull/291

**Comment by vconzola** [comment]
Looks like this was fixed. ^^ Closing.
