### ISSUE TITLE
Show the Mapping type in the Infrastructure Mappings list view

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#681]
We should show the mapping type in the list view now that we have multiple types (RHV and OpenStack). Question is where to put it?

**Comment by mturley** [comment]
@vconzola we have a couple of size/style choices for the `ListViewIcon` component here:

Small:
![screenshot 2018-10-09 18 29 49](https://user-images.githubusercontent.com/811963/46702577-ade7b300-cbf1-11e8-852e-11dc159238a1.png)

Medium:
![screenshot 2018-10-09 18 30 36](https://user-images.githubusercontent.com/811963/46702588-b50ec100-cbf1-11e8-801b-b2ec6ed24890.png)

Large:
![screenshot 2018-10-09 18 31 04](https://user-images.githubusercontent.com/811963/46702598-bcce6580-cbf1-11e8-947a-901a54d42775.png)

**Comment by mturley** [comment]
Vince says we'll keep this one as-is, for now. One possible solution might be to add a `<ListView.InfoItem>` at the front of the `additionalInfo` prop, with a static width and some text, but this clutters the row quite a bit. We might also wait until the brand team has icons for these products.

**Comment by mturley** [comment]
@vconzola did we still want to address this eventually? maybe we can just add some summary info to the top of the expanded content when you click each mapping?

**Comment by vconzola** [comment]
@mturley Let me go back and look at what the infra mapping view looks like today and where we could fit it in. My initial thought was to use product icons, but they were still being developed by brand. I'll check on the status of that too.

**Comment by mturley** [comment]
@vconzola Sounds good. Super low priority I'm sure, I just wanted to know whether to close this. Miq-bot is yelling at me about the same ~15 open issues it did 6 months ago 😆

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.
