### ISSUE TITLE
OSP Support: Require that the admin tenant is part of the mapping

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#701]
@vconzola @michaelkro , from Brett's email in the `Re: OSP Conversion Hosts` thread:

> > On Mon, Oct 8, 2018 at 1:23 PM Vince Conzola <vconzola@redhat.com> wrote:
> > Follow-up question... Does this also mean that the admin tenant must be included in the infrastructure mapping? In other words must at least one source cluster be mapped to the admin tenant or can the conversion host reside in a tenant that's not in the mapping?

> Conversion hosts will always be in the admin tenant so we will need to map to it as part of the infra mapping.

Currently, the Clusters step will allow you to proceed to the next step without mapping something to the admin tenant.

**Comment by vconzola** [comment]
@mturley @michaelkro I had a follow-up conversation about this with @bthurber over Slack. He said that as long as the admin tenant has a conversion host the source clusters don't need to be mapped to it. Here's the convo: 
vconzola [5:11 PM]
that seems to contradict what you said in your email? so are you saying that as long as the admin tenant has a conversion host none of the source clusters need to map to it. it just needs to be present with a configured conversion host.

bthurber [5:11 PM]
yes that is correct

**Comment by mturley** [comment]
I see, okay. Thanks for the clarification @vconzola.
