### ISSUE TITLE
[Code Cleanup] Incorporate <ListViewToolbar /> with other ListViews that have sorting, filtering, or pagination

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#716]
#709 introduced a new component, `<ListViewToolbar />` which encapsulates all the state and logic needed for sorting, filtering, and paginating `ListView`s in the V2V UI.  Using the render prop pattern, it is possible to share this code throughout our UI.  You can see the implementation and example usage in the PR referenced above.

Places where we can use this component
- PlanRequestDetailList (#761)
- PlanVmsList (#762)
- ~The migration ListViews on the Overview page~

Overview work handled by #729

**Comment by mturley** [comment]
@michaelkro I added `PlanVmsList` to the places we can use this component above. It doesn't currently have filtering, but it has sorting and pagination. I'll create two issues for the remaining two places we can use `ListViewToolbar` and we can treat this one as a catch-all.

For `PlanVmsList` (shown only on a plan that hasn't started) I wonder if we want to introduce filtering, and if so, what fields we would filter on? or if it should just behave as-is and not render any filter controls.

**Comment by michaelkro** [comment]
I'd imagine that it could be useful to filter by name.  A possible use case could be if a user wants to double check that a particular VM is included in a plan.  If that plan has a large amount of VMs, it would be convenient to be able to quickly filter the list down.

That being said @vconzola, thoughts?

**Comment by mturley** [comment]
I broke out the two remaining pieces of this into #761 and #762, this issue should be closed when those are both closed.

**Comment by vconzola** [comment]
@michaelkro What's the difference between PlanRequestDetailList and PlanVmsList?

**Comment by michaelkro** [comment]
@vconzola 

`PlanRequestDetailList` is the details view for plans in the following states
- in progress
- complete
- archived

`PlanVmsList` is the details view for not started plans.  It's a way for users to see what VMs will be migrated under a plan.

**Comment by vconzola** [comment]
@michaelkro OK, thanks. Then I agree it would be useful to be able to filter on all of these lists. But what filter are we talking about here - the PF textbox filter, not the general search filter, correct?  You guys are going rogue on me. I think we need more bugs to y'all focused.  :-)

**Comment by michaelkro** [comment]
Hahaha, it's the newly discovered pirate in my @vconzola 

It would be the same filtering that we use in the toolbar for the other ListViews.  Actually, now that I look, it looks like filtering is already there @mturley 

<img width="1797" alt="menubar_and_manageiq__migration" src="https://user-images.githubusercontent.com/15141412/47918264-75e72f00-de82-11e8-8738-e17700c8c969.png">

**Comment by mturley** [comment]
#777 should wrap this one up.
