### ISSUE TITLE
[MIQ Vert Nav] Migration menu items do not behave the same as other sections

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#717]
# Expected Behavior
For example, if you navigate to

```
Storage -> Block Storage -> Volume Backups
```

navigate away, and then click on

```
Storage -> Block Storage
```
It takes you back to Volume Backups automatically

# Current Behavior
If you click on

```
Compute -> Migration -> Infrastructure Mappings
```

navigate away and then click on

```
Compute -> Migration
```

It takes you to Overview instead of back to Infrastructure Mappings

**Comment by michaelkro** [comment]
Related https://github.com/ManageIQ/manageiq-v2v/issues/726

**Comment by mzazrivec** [comment]
This problem boils down to the fact, that currently the first menu item points to `/migration` and second one to `/migration#/mappings`.

ManageIQ (the ruby part) remembers just the url part (i.e. everything after `#` is ignored), so anytime
you click on `Compute -> Migration`, you'll get redirected to `/migration`, which is the first menu item.

One way to resolve this would be to support remembering `/url#fragment` by ManageIQ.

Another way would be to have two ruby conrollers, or at least two methods in the same controller. Though this I guess would mean page reloads anytime you'd click between those two menu items.

Thoughts?

**Comment by himdel** [comment]
Indeed, ideally we should be using a proper (js-side) router instead of Hash router, and then it would work.
@Hyperkid123 is probably more aware of what's stopping us there.

I don't see a problem with remembering `url#fragment` *if* that comes from the menu item.

But we probably can't ever support remembering custom `url#fragment` coming from the user, so this would only work when clicking the menu item, not necessarily when accessing the URL.

**Comment by himdel** [comment]
Or, another alternative .. if we rewrite all menu handling in javascript, we can just ask the router.
Not trivial though :).

**Comment by Hyperkid123** [comment]
@michaelkro @himdel the React routing right now is using hash routing. Its the most "friendly" way how to do client routing on pages that use both ruby and React (I know that is not the case for v2v). Unfortunately this means that tou routing history is not persisted on the backend and when you leave the page, it is lost.

What we can do, is listen on this history changes (that is very easy) and store the current hash route to some place from which we can take it when we are mounting React component and push/replace hash history. LocalStorage is good candidate for this.

That is probably the easiest way how we can handle it, without rebuilding half if the app.

**Comment by michaelkro** [comment]
I'm totally OK with having full page reloads when using the vert nav, since, as @himdel mentions, this is consistent with the rest of the application.

I like the idea of using local storage to store the current route that @Hyperkid123 suggests, as this would be very useful to have, but maybe as a followup.  It would be nice to first get on the same page as the rest of the UI first :)

**Comment by AparnaKarve** [comment]
@mzazrivec - Great description of the problem...using two ruby controllers/two methods in the same controller was what I was comtemplating as well.

I was also mostly trying to solve the other larger issue (well, larger in my eyes) -- full page reloads!

After having seeing how the routing happens with react-router and how blazing fast it is (since it does not hit the server), a full page reload does not look too appealing.

While it would be really nice if we could do the React routing if already in the Migration realm -- I think it is OK to put this as a wish-list item for now.

**Comment by martinpovolny** [comment]
As @Hyperkid123 wrote the hash routing is the only way to make React routing work while rest of the app is routing via in Rails.

As @mzazrivec hinted: for several menu items there should be several controllers. Thats what we where working towards and that's the asumption that makes the menus work. But this asumption is broken by V2V.

I understand that it's not feasible to break the V2V into multiple controllers at this stage. That could have been done earlier. Now it would be a too big change.

Same as @himdel wrote I also don't see a problem with remembering url#fragment if that comes from the menu item. And for the menus to properly work we don't need to support remembering custom url#fragment coming from the user.

I think that we should look into remembering the url#fragment and fix the issue that way unless while doing so some problem appears. It that happens we can look into remembering current hash route in the LocalStorage as @Hyperkid123 suggested.

**Comment by martinpovolny** [comment]
Except the plan is not going to work. Following a discussion with @mzazrivec I checked and:

https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/layouts/_vertical_navbar.html.haml#L42

We generate a normal `<a href=...` link meaning the browser will not talk to the server when navigating from `url#onehash` to `url#seconthash`.

The link params are here https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/presenters/menu/item.rb#L39

There's the `miqCheckForChanges` javascipt call aready done there on click so possibly we can do some crazy stuff such as assynchonously telling the server that the menu navigation was uses.

But generally this means a good-bye to a simple & clean & isolated fix.
