### ISSUE TITLE
[Overview] Auto select displayed migration plans

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#723]
Instead of always defaulting to showing `Not Started Plans`, use the following priority to determine which plans to show the user when landing on the Overview page

1.  Plans in progress, if there are any
2.  Not started plans, if there are any and (1) is empty
3.  Completed plans if there are any and (1) and (2) are empty
4.  Archived plans if there are any and (1), (2), and (3) are empty

https://bugzilla.redhat.com/show_bug.cgi?id=1642464

**Comment by michaelkro** [comment]
Question:  Do we want to auto-select the displayed plans the first time or every time the user visits the Overview page?

@vconzola

**Comment by vconzola** [comment]
@michaelkro IIUC, everytime. Once at least one plan has been created there should never be an empty state displayed by default. Is that your question?

**Comment by vconzola** [comment]
@michaelkro One possible exception to the 4. rules listed above... If possible, when returning to the Overview page from the Create or Edit Plan wizards we should display Not Started plans.

**Comment by michaelkro** [comment]
Also, I am assuming that we will default to Plans not Started if there are no plans of any type but there exist at least one mapping

**Comment by michaelkro** [comment]
> One possible exception to the 4. rules listed above... If possible, when returning to the Overview page from the Create or Edit Plan wizards we should display Not Started plans.

This should be handled automatically by the create/edit process, but I'll double check

> IIUC, everytime. Once at least one plan has been created there should never be an empty state displayed by default. Is that your question?

My question is more with regard to behavior.  If, say, the user is viewing the details of a completed plan, returning to Overview currently returns the user to the last state, i.e., viewing completed plans.  But if we always pre-select the displayed plans according to the priority list, this will change

**Comment by michaelkro** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1642464
