### ISSUE TITLE
Upstream Appliance - Migration menu items not selected 

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#726]
When we navigate to `Compute->Migration->Overview` or `Compute->Migration->Infrastructure Mappings` the Menu items it vertical navigation menu should be highlighted as selected. 

**NOTE:** Fix required before next downstream build.

**Comment by michaelkro** [comment]
Related https://github.com/ManageIQ/manageiq-v2v/issues/717

**Comment by mzazrivec** [comment]
@miq-bot assign mzazrivec

**Comment by michaelkro** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1642104
