### ISSUE TITLE
Infra Mapping jumping around atomatically

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#728]
![peek 2018-10-23 10-29](https://user-images.githubusercontent.com/8180469/47368101-04072c80-d6af-11e8-87e3-65118eb412d5.gif)
These infra mappings keep jumping across the page all the time. We should fix it.

**Comment by michaelkro** [comment]
@kedark3 by chance, is the appliance you're seeing this on still up?

**Comment by kedark3** [comment]
Please check my message on Gitter

**Comment by michaelkro** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1643295

**Comment by michaelkro** [comment]
@kedark3 this may have been resolved by https://github.com/ManageIQ/manageiq-v2v/pull/736, which has already been backported.

When you have a moment, can you check to see if this is still happening on the QE appliances?  Thanks! :)

**Comment by kedark3** [comment]
Just validated this on CFME 5.10.0.21 build. Things are not jumping around. Closing this issue.
