### ISSUE TITLE
v2v - Enhanced Error Reporting in UI from virt-v2v log

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#734]
This is a RFE BZ, Fabien and Brett will need to collaborate with UI team to discuss this.
https://bugzilla.redhat.com/show_bug.cgi?id=1595365

**Comment by bthurber** [comment]
@vconzola do you mind reviewing?  I think this may require some discussion to see what we can expose in the UI.

**Comment by vconzola** [comment]
@bthurber Yeah, I think this will require a discussion. We can provide more detailed error information in the UI, but we can't generate that information. It will have to come from the backend.

**Comment by mturley** [comment]
After discussion with @fdupont-redhat, he is going to make a PR to add this enhanced error message to the task objects at `task.options.progress.states[task.options.progress.current_state].message`, which we'll need to expose in the UI. @vconzola I'm thinking we can just add a "Message:" line to the existing popover on a migration task, here:

![Screenshot 2019-03-18 12 52 48](https://user-images.githubusercontent.com/811963/54547854-f95e7400-497c-11e9-9176-e27a2f69765c.png)

Does that work for you?

**Comment by mturley** [comment]
Note to self: this will depend on https://github.com/ManageIQ/manageiq-content/pull/514

**Comment by fdupont-redhat** [comment]
Backend and automate PRs are merged. Have fun exposing the message in the UI :)

**Comment by mturley** [comment]
Thanks @fdupont-redhat! This is near the top of my list, I'll let you know when I have a PR ready.

**Comment by mturley** [comment]
@fdupont-redhat here's the PR for this one: https://github.com/ManageIQ/manageiq-v2v/pull/918
