### ISSUE TITLE
[Overview] Empty state copy needs to be updated

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#735]
https://bugzilla.redhat.com/show_bug.cgi?id=1643529

The current text still refers to the dropdown that was removed

# Screens
<img width="1920" alt="fullscreen_10_25_18__11_07_am" src="https://user-images.githubusercontent.com/15141412/47510498-43b44c80-d846-11e8-9dd1-4eeb1496baba.png">

**Comment by michaelkro** [comment]
I'm thinking about just removing the second line from the body text.  Is this ok, or is there anything you'd like for me to change the current message to @vconzola?

**Comment by vconzola** [comment]
@michaelkro yeah, just remove the second line.

**Comment by michaelkro** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1643529
