### ISSUE TITLE
 [v2v] Cancel Migration does not work

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#737]
Please see BZ for details : https://bugzilla.redhat.com/show_bug.cgi?id=1630013

**Comment by bthurber** [comment]
Fixed by:  https://github.com/ManageIQ/manageiq-content/pull/457

**Comment by michaelkro** [comment]
Closed by https://bugzilla.redhat.com/show_bug.cgi?id=1614864
