### ISSUE TITLE
[v2v] Fail migration if no conversion host configured

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/manageiq-v2v#739]
BZ link:  https://bugzilla.redhat.com/show_bug.cgi?id=1640816

Issue:
When initiating a migration plan, if there are no conversion hosts available the migration plan spins until the 40K timeout has been reached.

Resolution:
If there is no conversion host available fail the migration and provide a reason why in the UI.

**Comment by kedark3** [comment]
:+1:

**Comment by michaelkro** [comment]
Case where there are no configured conversion hosts.  The request will be denied.

**Comment by mturley** [comment]
I think this is a duplicate of #786 (or that is a duplicate of this). Since we've referenced #786 in my WIP PR (#798) and elsewhere already, I'll put the BZ link over there and mark the PR as closing both issues.
