### ISSUE TITLE
[v2v] Migration plan spins

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/manageiq-v2v#740]
BZ link:  https://bugzilla.redhat.com/show_bug.cgi?id=1640816

Issue: 
If a conversion host is busy with migrations and no other's are available, a newly initiated migration plan will appear to spin without a reason.  The reality is the plan and VM's are in queue waiting to be processed.

Resolution:
Provide a migration plan cancel button and a reason why the plan hasn't begun.  I.E. "waiting on conversion host".

**Comment by kedark3** [comment]
:+1:  Thanks Brett for taking this action.
