### ISSUE TITLE
v2v - Expose number of concurrent migrations per conversion host in UI

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/manageiq-v2v#747]
Issue:
Expose this in the Migration UI so that consumers can change how many concurrent VM migrations are allowed per conversion host

BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1613848

**Comment by bthurber** [comment]
@vconzola FYI

**Comment by vconzola** [comment]
@bthurber Is this something we want to get into 1.1?

**Comment by bthurber** [comment]
@vconzola yes.  This will be our first step into the advanced throttling post 1.1.

**Comment by vconzola** [comment]
@bthurber OK. So, if I'm reading the comments in the BZ correctly, we just need to add a setting for maximum number of concurrent migrations across all conversion hosts. And the default value should be 10. And the backend will decide how those get allocated among the conversion hosts if there's more than one? Correct?

**Comment by bthurber** [comment]
@vconzola yes.  Need to sync with Fabien on behavior.

**Comment by mturley** [comment]
@bthurber is there already API support for reading/writing this new setting, or is that still in development? I'm starting on the UI part of this in https://github.com/ManageIQ/manageiq-v2v/issues/776.

**Comment by mturley** [comment]
Copying here from Gitter for visiblilty:

@fdupont-redhat I have a question about updating settings with the /api/settings endpoint as documented here: http://manageiq.org/docs/reference/latest/api/reference/settings#updating-settings

I can `GET /api/settings` and find the `transformation.limits.max_concurrent_tasks_per_host` value I'm looking for, but I can't `PATCH /api/settings`, that's a 404. Instead I have to `PATCH /api/servers/:id/settings`. In my dev environment there are two servers.. how can I tell which one the UI needs to update? do I need to update all of them? I'm confused about which one provides the data for /api/settings with no server id. It looks like I can set this at the zone and region level as well. Not sure how the UI should decide which settings to update.

It looks like I can `GET /api` and look at `server_info.server_href` to find the current EVM server, and then use that for settings. When you get a chance @fdupont-redhat can you confirm that's what we want here?

**Comment by mturley** [comment]
Ok, thanks @fdupont-redhat. I'll update my PR to set it on all servers rather than the current server.
