### ISSUE TITLE
Migration plans should be hidden if any of RHV or VMware providers are missing

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#748]
https://bugzilla.redhat.com/show_bug.cgi?id=1609921

**Comment by michaelkro** [comment]
@vconzola

**Comment by bthurber** [comment]
@vconzola @michaelkro thoughts on this?

**Comment by vconzola** [comment]
@bthurber this is one of the issues i mentioned in my email earlier today that we're working on, but likely won't have an elegant solution for before 12/4. the ui will have to check every cluster, lan, datastore, cloud_tenant, cloud_network, and cloud_volume_type and then iterate through every mapping and its mapping items to determine if it is valid. this is what i mean by not elegant.  

we definitely should not "hide" migration plans. if a plan has a broken mapping we can disable the Migrate button, but if it's a scheduled plan it will have to start and then fail. @michaelkro tested this and it fails (somewhat) gracefully. the ui does not crash. 

just fyi, this issue, #749, #754, and #766 are all related and will be tracked through #766.

**Comment by bthurber** [comment]
@vconzola ack.  I moved the BZ to 5.10.1 z-stream.

**Comment by mturley** [comment]
Closing this as it was decided in the BZ that we won't hide plans, but instead we'll display more meaningful error messaging. That work will be tracked instead in https://github.com/ManageIQ/manageiq-v2v/issues/877.
