### ISSUE TITLE
[Infra Mappings] Editing a mapping missing clusters/datastores/networks crashes app

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#749]
https://bugzilla.redhat.com/show_bug.cgi?id=1644399

**Comment by mturley** [comment]
@vconzola, while we are waiting for more info on #754, I wonder if we should make a stopgap fix for this bug to prevent the possibility of the app crashing? perhaps just block the edit icon and display a warning popover when you click it that just says something like "A mapping with missing clusters, datastores or networks cannot be edited"?  or should we wait for #754 to be figured out before we block the edit operation at all?
