### ISSUE TITLE
Edit a plan for which a mapping doesn't exist

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#752]
For the case where the mapping associated with a plan is invalid (provider deleted or mapping deleted), we need to be able to edit the plan. Currently, edit is disabled in this case. 

This a change in design direction to improve the user experience. When the user goes into Edit Plan and changes the infra mapping all succeeding steps will be as if creating a new plan. We should warn the user on Next that all information for the current plan will be lost.

**Comment by mturley** [comment]
I implemented the clearing of all succeeding steps when changing the mapping in https://github.com/ManageIQ/manageiq-v2v/pull/757, although I did not add a warning in that PR. @vconzola when you get a chance to mock up the design for that warning I can add it to that PR, or we can follow up with another PR.

**Comment by vconzola** [comment]
This issue is expanding to include the ability to change the mapping when editing any migration plan. Here's a mockup of the warning that will be displayed if the user selects to change the mapping:
![9a1-createplan-general](https://user-images.githubusercontent.com/22823035/47919883-fd36a180-de86-11e8-8db3-13af3ea49ad7.png)
Note: If the mapping for the plan does not exist (provider deleted or mapping deleted), then the warning will not be shown and the dropdown will display it's empty (Choose) state.

@mturley How do we handle the condition where no mappings exist when we go to edit the plan? Should we have an error message on the first page of the wizard that just says no mappings exist and closes the wizard?

**Comment by vconzola** [comment]
THis was a bad idea...
