### ISSUE TITLE
[Infra Mapping Wizard] "All source clusters have been mapped" appears even when "No clusters found"

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#759]
Screenshot from @kedark3:

![screenshot-from-2018-11-01-11-40-07](https://user-images.githubusercontent.com/811963/47868525-bf7c3f00-ddda-11e8-80e9-1acb950907bf.png)

We should test to make sure this also doesn't happen on the Storage and Networks steps.

**Comment by kedark3** [comment]
I will open a BZ and link it here shortly .

**Comment by kedark3** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1645250
