### ISSUE TITLE
[Plan Wizard/Plan ListItems] Handle plans with broken infra mappings

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#766]
https://bugzilla.redhat.com/show_bug.cgi?id=1666840

# The Situation
It is possible for a not started plan to be associated with a "broken mapping".  In this case, there is no indication that anything is wrong on the Overview page.  All actions in the plan ListItem, including Migrate, are enabled

# What is a broken mapping?
The following are ways to break a mapping that we know about.  There may be others yet to be discovered
* Remove, and then re-add a target provider
  * When a target provider is removed, all of its clusters are deleted from the db, and after it is re-added, its clusters have new IDs.
  * Every mapping configured to migrate to that target provider expect the clusters to have the old IDs, so they all break
* Remove, and then re-add a source provider
  * Likely similar to the target provider case.
  * I don't know how to re-add a source provider, so have not been able to confirm in dev
* Remove an individual cluster/network/datastore
  * Assume that the subset of mappings containing the specific item that has been removed will break due to either the source or destination ID not matching what is in the db
  * Do not know how to re-add these resources after removal, so have not been able to confirm in dev

# Questions and things to do
* Display a warning in the plan's ListItem if its mapping is broken.  (Not started plans and failed completed plans that can be retried)
* If a not started plan has a broken mapping, do we disable the `Migrate` and `Schedule` buttons?
* Should we filter the mappings to choose from in the General step of the Plan Wizard to remove broken mappings?
  * A plan with a broken mapping can be edited to choose a new mapping, but currently it is possible to switch to another broken mapping
  * Further, if a mapping's source cluster data no longer matches what is in the db, the Vm discovery/validation service will likely fail

**Comment by mturley** [comment]
> Should we filter the mappings to choose from in the General step of the Plan Wizard to remove broken mappings?

For the reasons you specify above, I think the answer here is yes. This then presents the question, what do we do when all of the mappings are broken (there will be none to choose from)? The General step of the plan wizard may need to detect this, show an error, and close the wizard.

**Comment by mturley** [comment]
For the purposes of determining in the UI whether a mapping is broken or not, we should come up with a specific definition of what "broken" means in terms of the data presented by the API. Do we need to run through all of the clusters. datastores and networks in the mapping and check that their original resources still exist? Or would it be sufficient to check some subset of these resources?

**Comment by vconzola** [comment]
@bthurber for your awareness and comment. this is related to the issue KK found where the UI crashed when he attempted to edit a broken mapping. We started looking into the implications for plans associated with broken mappings. This is the outcome.

**Comment by bthurber** [comment]
@vconzola ack.  Your suggestion sounds reasonable.

**Comment by michaelkro** [comment]
https://github.com/ManageIQ/manageiq-v2v/issues/749

**Comment by michaelkro** [comment]
https://github.com/ManageIQ/manageiq-v2v/issues/748

**Comment by michaelkro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPIKE - TransformationMapping model validation](https://trello.com/c/w3NMX2zH/218-spike-transformationmapping-model-validation)

**Comment by mturley** [comment]
https://github.com/ManageIQ/manageiq-v2v/issues/754

**Comment by mturley** [comment]
The remaining work to be done here is tracked in the following three issues: #754 (relatively small amount of work, #877 and #878 (both involve heavy refactoring)

**Comment by mturley** [comment]
I think it's safe to close this one since we have the smaller issues open for the individual cases.
