### ISSUE TITLE
[Automation Test Request] filterFieldTypeMenu button should have unique `Name`

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#771]
![image](https://user-images.githubusercontent.com/8180469/48015082-332d8d00-e0f6-11e8-8dd7-7c8fad30599c.png)

`filterFieldTypeMenu` button should have unique `name` attribute (e.g. `vms-filter-dropdown` or something logical) so that I can select it using that attribute. Currently, there are Dropdowns at multiple places on page with exact same `id` and `class` attributes E.g. on `Migration Not Started`, `Migration Complete` and `Migration Plans Archived` pages, all have a dropdown with exact same `class` and `id`. Hard for my automation to differentiate.

**Comment by michaelkro** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1646657
