### ISSUE TITLE
Add Max Concurrent Migrations Setting to the UI

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#776]
As a first step toward migration throttling we need to add a setting for maximum concurrent migrations. Mockup:
![migration settings page](https://user-images.githubusercontent.com/22823035/48079648-c54a9980-e1b9-11e8-8fb1-678183348367.png)
Notes:
Default value is 10.
Apply button is disabled until the selected value is changed. When Apply is selected disable the button until we know that the change was successful.
Will provide text for the tooltip later.

**Comment by bthurber** [comment]
@vconzola not sure.  I believe it is part of the backend.  Should know more after our meeting Thursday.
