### ISSUE TITLE
 [v2v][osp] Migration stalls if Key Pair is not added to OSP provider, and no warning/error given 

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#794]
https://bugzilla.redhat.com/show_bug.cgi?id=1650340

**Comment by michaelkro** [comment]
As per Brett

> This situation only happens when there is no RSA key pair configured for the OSP provider.  There is no warning in the IMS UI indicating no key pair added.  It knows of the conversion appliances so no warning is present.

**Comment by michaelkro** [comment]
We need to determine whether or not this information is available to us via CF

**Comment by bthurber** [comment]
@vconzola any updates on this?

**Comment by vconzola** [comment]
@bthurber we thought we got this one when we made the changes for no conversion host. the no key pair part slipped thru the cracks. @michaelkro is working on it now, but we not only need to add the warning to infra mapping wizard, but we also need to display an error and fail the migration if a plan gets executed using an OSP provider with no RSA key pair (similar to what we added for no conversion host). so likely this won't get in today and will require a blocker if it's needed for GA.

**Comment by michaelkro** [comment]
#833 adds warning icons on the clusters step.

Similar to the conversion host warning icons for RHV targets, for each available cloud tenant we check that its OSP provider has a RSA key pair.  If it does not, we render a warning icon with a popover.

We still need to handle cancelling a migration plan that was started before adding the RSA key pair.

**Comment by michaelkro** [comment]
Closed by #833 and #836
