### ISSUE TITLE
Phase 2 of vertical menu fixes

### ISSUE THREAD

**Issue by mzazrivec** [ManageIQ/manageiq-v2v#811]
Pull request https://github.com/ManageIQ/manageiq-v2v/pull/769 fixed several issues regarding vertical menu. With that PR in place, vertical menu highlighting works as expected. An unfortunate effect of this PR though is loss of navigation history and client side routing (I replaced `ConnectedRouter` with `BrowserRouter`).

Here's what I'm proposing to remedy the above:

1. We'd have 3 menu items for migration (and also 3 rails routes in the plugin). That way we'd have vert. menu updates whenever we click on some of the migration menu items.
2. We'd go back to using ConnectedRouter and Link, which would give us back navigation history.
3. on the backend (or better yet classic-ui) side, we'd have an action, let's call it vertical_menu_ping(), which the client (v2v react in this case) would call anytime it would navigate between overview, plain id and migration mappings screens. This backend routine would update vert. menu data in server session.

**Comment by mturley** [comment]
This sounds like a great solution, and I also just want to tack on this issue I made to track things that we'll want to follow up on as part of this: https://github.com/ManageIQ/manageiq-v2v/issues/803
