### ISSUE TITLE
Plan Wizard: Add support for OSP flavor and security group columns in CSV import

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#842]
When uploading a CSV file containing VMs to migrate in the Plan Wizard, users should be able to pre-select the OSP security group and flavor to be used for each VM (currently only available as dropdown menus on the Instance Properties step) by including optional CSV columns labeled "Security Group" and "Flavor".

If a group or flavor name specified in the CSV matches one of the available options, the dropdown menu should have that option selected upon entering the Instance Properties step.

If a group or flavor name specified in the CSV **does not** match one of the available options, the existing default (best fit) should be used, and the user should be warned in some way that their CSV value was not used.

**Comment by vconzola** [comment]
@mturley Here's a mockup for the security group warning. The tooltip is displayed when the user clicks on the warning icon. Invalid flavors would work the same way.
![new wireframe 1](https://user-images.githubusercontent.com/22823035/50610522-431cdf80-0ea1-11e9-9abe-596b9b02ffb0.png)

**Comment by bthurber** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1666352
