### ISSUE TITLE
Conversion Host Enablement - Configuration Wizard

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#855]
Create a wizard for configuring conversion hosts for RHV or OSP.

Mockups to follow.

Part of the conversion host enablement feature: https://bugzilla.redhat.com/show_bug.cgi?id=1622728

**Comment by mturley** [comment]
@vconzola when you get a chance (if it's something you're ready to determine) the first thing we'll need here is simply a list of the names of each wizard step, so we have a basis for labels and filenames.

**Comment by vconzola** [comment]
Mockups: 
[Conversion Host wizard.pdf](https://github.com/ManageIQ/manageiq-v2v/files/2797454/Conversion.Host.wizard.pdf)

**Comment by vconzola** [comment]
@mturley I added a link to the mockups above, but don't consider those step names final.

**Comment by mturley** [comment]
Closing this since the remaining parts of the wizard were moved to #898, #899, #903 and #881.
