### ISSUE TITLE
Conversion Host Enablement - Conversion Hosts Listview

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#856]
This will be displayed under the Conversion Hosts tab of the Migration Settings page once at least one conversion host has been configured. 

Mockup to follow.

This is broken down into the following issues and should be closed when all of these are closed: #860, #861 and #862

Part of the conversion host enablement feature: https://bugzilla.redhat.com/show_bug.cgi?id=1622728

**Comment by mturley** [comment]
We could possibly break this down into the following steps:
* Create a basic list view with placeholder list items (only the conversion host name, for example)
* Flesh out the list items with read-only data including status information
* Add action buttons to the list items and wire them up to API requests

**Comment by mturley** [comment]
Note: for fetching the tasks in progress which are configuring new conversion hosts (which we will need to append/prepend to the list of conversion hosts already configured), we can use this API request: `/api/tasks?expand=resources&attributes=id,name&filter[]=name="%25conversion_host%25"`

**Comment by mturley** [comment]
Another note about the `conversion_host` tasks API request: we'll want to filter them to get only the non-completed ones. @djberg96 gave me a hint about adding `filter[]=state=queued` for the queued tasks, but we'll probably need a filter like `name="%25conversion_host%25" AND (state=queued OR state=finished)`. I'm not sure exactly how to assemble that boolean logic in these API filters.

Relevant docs: http://manageiq.org/docs/reference/fine/api/overview/filtering

**Comment by djberg96** [comment]
`http://localhost:3000/api/tasks?expand=resources&attributes=id,name&filter[]=name="%25conversion_host%25"&filter[]=state=queued&filter[]=or state=Finished`

**Comment by djberg96** [comment]
For now you can do "*ueued" and "*inished".

**Comment by mturley** [comment]
Awesome, thanks @djberg96. @mzazrivec we'll have to use the above API filter for one of the phases of the list view. Not sure whether that'll be part of what you're doing now or the next part.

**Comment by mturley** [comment]
Sorry @djberg96 I misspoke above, we'll need `queued or in-progress`, not `queued or finished`. Do you know what that in-progress state value is?

**Comment by djberg96** [comment]
@mturley Just looking at miq_task.rb, there are four possible states - "Initialized", "Queued", "Active", "Finished". So, I'm assuming "Active" is what you're looking for.

**Comment by mturley** [comment]
Perfect, thanks.

**Comment by vconzola** [comment]
@mturley Here you go: 
![screen shot 2019-01-25 at 2 52 00 pm](https://user-images.githubusercontent.com/22823035/52730265-f12fa500-2f88-11e9-8940-c0c9076d11f5.png)

**Comment by mturley** [comment]
Thanks @vconzola.

@djberg96, one more question here: do you know what happens to the task object when configuration has failed? is that still a `Finished` state? I guess the real filter we need here is "anything that's not finished successfully". Sorry to keep going back and forth on this one.

**Comment by djberg96** [comment]
On the raw task object there are two separate columns, `state` and `status`. The possible values for status are "Ok", "Warn", "Error", "Timeout", "Expired" and "Unknown". I would think if a task fails, then it's necessarily finished, but I'd have to ask to be certain.

**Comment by djberg96** [comment]
On a side note, the `MiqTask` model does have some baked into scopes like `completed_ok`, `running`, `finished`, and so on, but I'll have to double check to see if they're accessible by the rest api and if they would be useful to you.
