### ISSUE TITLE
Conversion Host Enablement - Listview #2 - Add action buttons to the list items

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#861]
This is part 2 of 3 for #856.

This is where we'll start to connect list items to API requests. @vconzola do you have a list of all the actions we can perform on an already-configured conversion host?

Part of the conversion host enablement feature: https://bugzilla.redhat.com/show_bug.cgi?id=1622728

**Comment by vconzola** [comment]
@mturley The only actions will be Remove and Download Log. I'll update the mocks to reflect this.
