### ISSUE TITLE
RFE: Add a link/button to the Migrations Plans page to go directly to Infra Mappings page

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#865]
https://bugzilla.redhat.com/show_bug.cgi?id=1670703

This is an RFE from the QE team.

**Comment by mturley** [comment]
Assigning to myself and removing `needs-design` because @vconzola decided we should use the Breadcrumb Switcher pattern for this.

**Comment by vconzola** [comment]
Mockup:
![Context Selector-breadcrumb switcher](https://user-images.githubusercontent.com/22823035/58490397-195ba200-813b-11e9-900d-ba9e24280c4a.png)
