### ISSUE TITLE
"Configure Providers" button in empty state takes user to page for VMW and RHV providers, but not for OSP.

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#875]
As pointed out by @michaelkro in https://github.com/ManageIQ/manageiq-v2v/pull/871#discussion_r253689717, when the user has insufficient providers configured, meaning they don't have at least one source provider (VMW) and at least one target provider (RHV or OSP) configured, we show a "Configure Providers" button that takes them to:

compute -> infrastructure -> providers

which is where a user would need to go to configure VMW and RHV providers, but not for OSP. Not sure what the best thing to do is here.

**Comment by vconzola** [comment]
@mturley Why can't you configure OSP providers from the Providers page in CloudForms? Let's talk about this in our sync call tomorrow.

**Comment by mturley** [comment]
I actually don't know for sure, that's just what Mike said before he left. Clicking through it myself I see OpenStack as an option there, so I'm not sure what he meant. Maybe the backend guys will know.

**Comment by djberg96** [comment]
As per our bluejeans discussion, the confusion stems from openstack director (which is infra) vs openstack (which is cloud, and the one we want in this case).

**Comment by mturley** [comment]
Yes, I was wrong, we do need to direct users to `compute -> cloud -> providers` in addition to `compute -> infrastructure -> providers` when we have this "no providers" message.

**Comment by mturley** [comment]
@vconzola I saw you had a mockup for this in the standup today, do you mind linking that here when you get the chance?

**Comment by vconzola** [comment]
Mockup: 
![Empty State - no providers](https://user-images.githubusercontent.com/22823035/58490900-f978ae00-813b-11e9-8f18-09969f1f6d92.png)
