### ISSUE TITLE
[Plan ListItems] Plans with broken mappings should display a warning and disable schedule/migrate buttons

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#877]
Part of https://github.com/ManageIQ/manageiq-v2v/issues/766.

In the Plans listview
   a. Display a warning icon adjacent to the name of the associated mapping for plans with broken mappings.
   b. Disable the schedule and migrate buttons for plans with broken mappings.

This will involve a lot of heavy lifting, as the code to detect a broken mapping is currently tightly coupled to the mappings list view and we don't load all the necessary resources in the plans list view.

Related to #878, might need to share some of the same refactoring. We'll probably need to load all the clusters, datastores and networks in a new common reducer, so that data can be shared among these three views.

**Comment by mturley** [comment]
@vconzola we'll need to figure out a priority for this, or perhaps decide that it's not feasible to do. Brett's comment in the `Infrastructure Mapping rebuild` email chain may also apply to this:

> IMO this is a very stretch use case and the amount of development effort outweighs the issue.  We should already have a warning in the docs.

**Comment by mturley** [comment]
@vconzola I can't remember where we landed on this, I'll punt it for another 6 months to shut up miq-bot, but do you remember if we decided to do anything about it in the UI, or if it should be handled by the backend somehow? cc @fdupont-redhat

**Comment by fdupont-redhat** [comment]
Another thing to check came to me: do all the VM still match the mappinng? Between the plan creation and the migration time, some VMs might have been migrated to another datastore that is not mapped. Something difficult to see. We should have an event driven validation of the objects, but to be honest it's going to require a big effort on the backend. Not sure it's worth it.

I'm fine with silencing miq-bot for 6 another months and revisit later.

**Comment by mturley** [comment]
Sounds good. I'll leave this open to revisit later, and I'll close the related issues https://github.com/ManageIQ/manageiq-v2v/issues/754 and https://github.com/ManageIQ/manageiq-v2v/issues/878. If we end up fixing this in the future we can address those cases as well.

**Comment by mturley** [comment]
Feel free to reopen this if you disagree @fdupont-redhat, but I think at this point this is a `wontfix`.
