### ISSUE TITLE
[Create Plan wizard] Remove broken mappings from the mapping selection dropdown

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#878]
Part of https://github.com/ManageIQ/manageiq-v2v/issues/766.

This will involve a lot of heavy lifting, as the code to detect a broken mapping is currently tightly coupled to the mappings list view and we don't load all the necessary resources in the plans list view.

Related to #877, might need to share some of the same refactoring. We'll probably need to load all the clusters, datastores and networks in a new common reducer, so that data can be shared among these three views.

**Comment by mturley** [comment]
@vconzola we'll need to figure out a priority for this, or perhaps decide that it's not feasible to do. Brett's comment in the `Infrastructure Mapping rebuild` email chain may also apply to this:

> IMO this is a very stretch use case and the amount of development effort outweighs the issue.  We should already have a warning in the docs.

**Comment by mturley** [comment]
Same here @vconzola @fdupont-redhat. This requires running the same validations as https://github.com/ManageIQ/manageiq-v2v/issues/877 outside the context of the mappings page (a real pain in the ass to do in the UI).

**Comment by fdupont-redhat** [comment]
@mturley then close both. Our priority is Warm Migration. Then in 2020 it's going to be OpenStack to OpenStack. As said in #877, this validation should happen in the backend and be event driven.

**Comment by mturley** [comment]
Sounds good, thanks @fdupont-redhat!
