### ISSUE TITLE
[Configure Conversion Host wizard] Add validation button to VDDK library path field on the Authentication step

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#881]
In the mockups for the Authentication step of the wizard, we have a Validate button on the VDDK library path button. I left that out of the initial PR for this wizard step since it requires some API support that is still in development. We'll need to go back and add that validation.

<img width="831" alt="screenshot 2019-02-13 16 00 04" src="https://user-images.githubusercontent.com/811963/52743766-cc4b2a00-2fa8-11e9-97a7-898bcf764b9c.png">

**Comment by mturley** [comment]
@fdupont-redhat is this VDDK path validate button something we still want to add eventually, or should I close this issue?

**Comment by fdupont-redhat** [comment]
@mturley you can close it for now. So far, we don't have requests from field and it's been there for 6 months.

**Comment by mturley** [comment]
Ack. Thanks @fdupont-redhat
