### ISSUE TITLE
[RFE] Add ability to Download Wrapper Logs from UI

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/manageiq-v2v#885]
**Description**
When anything goes wrong with the Migration, there are usually two files virt-v2v logs and virt-v2v-wrapper logs. These two files tell us what went wrong. Currently user can download virt-v2v logs from CFME UI. I request for adding ability to download Wrapper logs from UI. This can help user avoid going to conversion-host via SSH and hunt for files there. This is VERY IMPORTANT for easier debugging for users. Our Support people will be easily able to request users to provide these logs when needed as well. 

**Internal tracking**
https://bugzilla.redhat.com/show_bug.cgi?id=1655124

**Comment by mturley** [comment]
This feature will be complete when all of the following PRs are merged:
https://github.com/ManageIQ/manageiq/pull/18506
https://github.com/ManageIQ/manageiq-v2v/pull/887
https://github.com/ManageIQ/manageiq-v2v/pull/888
