### ISSUE TITLE
Conversion Host Enablement - Future Refactor - Entire history of tasks is loaded, we should instead load only the necessary tasks

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#895]
To display the status and enablement log of an enabled conversion host, we needed to associate each conversion host object with its original completed enablement task object. Due to the difficulty of this association, we didn't have a simple way of requesting from the API only the completed tasks matching the existing conversion hosts, so instead we load **ALL** conversion host tasks and make the associations in the UI, and we rely on parsing the task's name to get the resource name/type/id.

While it will work for this initial release, this isn't ideal for performance, and it theoretically could run into the 1000-record API pagination limit (see #891) if enough enable/disable tasks are present on the appliance. In the future, we should find a way to do this filtering on the back end, and make an API request that loads only:

* conversion host enablement tasks that are incomplete or failed
* conversion host enablement tasks that are complete, and correspond to existing configured conversion_host objects
* conversion host disablement (?) tasks that are incomplete or failed, and correspond to existing configured conversion_host objects.

@djberg96 let's keep track of this for post-1.1

**Comment by mturley** [comment]
Just to store this somewhere, here is the query Dan originally sent me for loading one of these tasks by resource id, maybe we could adapt this to load multiple tasks by these ids: `MiqTask.where("name ~* ?", '.*?conversion_host.*?resource=\(type:\s+[A-Za-z\:]+\s+id:6\)').map(&:name)`

**Comment by djberg96** [comment]
Eventually we'll want to establish a relationship from `ConversionHost` -> `MiqTask`, presumably through `MiqQueue`. This is trickier than it ought to be because of the way things are currently modelled, but should be possible. In addition, we'll want to make sure this is exposed in the REST API.

**Comment by mturley** [comment]
Ideally that would include a relationship from `MiqTask` -> resource (`Host` or `Vm`) too, so we could get the name, type and id of the resource before the `ConversionHost` exists.

**Comment by mturley** [comment]
It looks like this may be made possible by https://github.com/ManageIQ/manageiq/pull/18540.

**Comment by mturley** [comment]
Note to self: to test the implementation here, I'll need to get a database with completed conversion host enable tasks that include the `conversion_host.id` as provided by https://github.com/ManageIQ/manageiq/pull/18540.

**Comment by mturley** [comment]
Still should be done, but low priority.

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.

**Comment by mturley** [comment]
I may actually try to do this eventually.. reopening for now.

**Comment by mturley** [comment]
You were right last year @vconzola , sorry 😆 . Closing as `wontfix`.
