### ISSUE TITLE
Wizards have "skip-to-step" disabled, but hovering the step numbers still changes the background color

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#896]
In `ModalWizard`, when `stepButtonsDisabled` is true, we should also suppress the hover styles on those step numbers. This bug may have been duplicated upstream in the `WizardPattern` I contributed to `patternfly-react`, if so it should be fixed there too.

**Comment by mturley** [comment]
Still should be done, but very low priority.

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.
