### ISSUE TITLE
Conversion Host Enablement - List View - Download Log action - Need API support

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#902]
Part of the Conversion Hosts UI feature BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693339
(or maybe a followup BZ)

Originally part of #862, I'm hiding this kebab menu until the back end support is ready.

**We could release the Conversion Host settings page with this feature removed.**

Each conversion host enable/disable task has an associated playbook log file that the UI needs to be able to download with this Download Log kebab menu action:

![screenshot 2019-03-08 12 43 02](https://user-images.githubusercontent.com/811963/54045875-b80ddd80-41a0-11e9-85d9-a922003d3d4b.png)

The last I heard from back end discussions was that there still was not a way to redirect the output of the playbook to somewhere that the UI could download as a file.

**Comment by mturley** [comment]
@fdupont-redhat mentioned that the playbook output is stored in the `context_data` of the enablement task. We already associate the task with the host in the list view in order to show status details, so it should be pretty simple to implement a Download Log action that just takes the data from the task and writes it out to a file. I'll try to get this into CFME 5.10.5.

**Comment by fdupont-redhat** [comment]
@mturley in our lab, the output for enablement weighs about 4 KB when successful. When it fails, the log is likely to weighs the same.

**Comment by mturley** [comment]
Perfect, thanks @fdupont-redhat .

**Comment by mturley** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1705619
