### ISSUE TITLE
Conversion Host Enablement - Configuration Wizard - Add tooltip/popover explaining VDDK library path field

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#903]
~~Part of the Conversion Hosts UI feature BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693339
(or maybe a followup BZ)~~ Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1705620

As a stopgap before we can implement https://github.com/ManageIQ/manageiq-v2v/issues/881, we agreed to add an info icon with a popover explaining the VDDK Library Path field on the Authentication step of the wizard.

@vconzola, I don't think a mockup is necessary, but can you help me figure out the text that should be in this popover?

**Comment by mturley** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1705620

**Comment by vconzola** [comment]
@mturley Let's have the popover say, "This is the location where you downloaded and saved the VDDK package, _VMware-vix-disklib-version.x86_64.tar.gz_."

**Comment by jerryk55** [comment]
@vconzola its still not clear to me whether this location is meant to exist on the conversion host or the appliance (or either), and whether it is meant to be a disk path or URL.

**Comment by mturley** [comment]
@vconzola I agree with @jerryk55, as a user I think I would still be confused as to whether it should be just a folder path or a full URL. I think it needs to be a URL, but we should get confirmation about that. The API param is called `vmware_vddk_package_url` and there was earlier discussion about validating it by just having the browser try to make a HEAD request at that URL (something we decided wouldn't work because of browser cross-origin security policy). So I'm pretty sure it's a URL.

@fdupont-redhat, would it make sense to tell the user "This is a URL for the location where you downloaded and saved the VDDK package, e.g. http://hostname/VMware-vix-disklib-version.x86_64.tar.gz." or something like that? Do we need to describe that it has to be served by an HTTP server? Should we maybe change the field in the UI from "VDDK library path" to "VDDK library URL"?

**Comment by mturley** [comment]
@bthurber, Vince mentioned you're covering for Fabien right now, do you have a moment to help us answer the above questions?

**Comment by bthurber** [comment]
It's a URL.  They will have to host it somewhere for access via http.

**Comment by mturley** [comment]
Thanks! @vconzola what do you think of something like "This is the location where you downloaded and saved the VDDK package, as a URL accessible via HTTP. e.g. http://hostname/VMware-vix-disklib-version.x86_64.tar.gz."

**Comment by vconzola** [comment]
@mturley  Sure. Looks good.
