### ISSUE TITLE
Polling code is duplicated in 4 places - should be abstracted away

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#904]
Brought up in this comment: https://github.com/ManageIQ/manageiq-v2v/pull/889#discussion_r264317063

We have API polling implemented separately in 4 places (`App/Overview/Overview.js` , `App/Mappings/Mappings.js` and `App/Plan/Plan.js` and now `App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js`. The Conversion Host implementation contains some subtle differences noted in the description of https://github.com/ManageIQ/manageiq-v2v/pull/889.

These should be abstracted into a polling helper of some kind. Maybe even a custom React Hook! 😄

**Comment by mturley** [comment]
Still should be done, but low priority.

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.
