### ISSUE TITLE
VMware folder view in migration plan wizard

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#914]
Mockup: 
https://drive.google.com/open?id=1bCrs1eaR-25dxwbXEzpLimotk5gG5Bz-

Say "Cluster" for the column header instead of "Source Cluster".

**Comment by vconzola** [comment]
Link to the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1593839

**Comment by mturley** [comment]
Note to self: follow this outline from Fabien on how to handle the data that should go in each column:

> I think that we can remove the provider name from the path. Then, the cluster is always under a specific datacenter, so we could move the datacenter into its own column, because you can have two clusters with the same name in two different datacenters. The folder is orthogonal to the cluster: a cluster groups hosts to form a HA or DRS set of machines, while the folder helps organize VMs and apply RBAC. So, the folder probably deserves its own column too. If we remove the provider and datacenter from the path, we can prefix it with a slash, to make it look like an absolute path. A VM that is not in a folder would appear in '/'. If we remove the allocated size, we should have enough space. We can also rename the 'Source Cluster' column to 'Cluster', as we're selecting source VMs.

> To summarize my proposal, we would have 4 columns:
> * VM Name
> * Datacenter
> * Cluster
> * Folder (instead of path)
