### ISSUE TITLE
[BZ#1694741] Completed Migration plans cannot be ordered by execution order

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#927]
https://bugzilla.redhat.com/show_bug.cgi?id=1694741

In the Migration Plans Completed and Migration Plans Archived views, add a sort option for the creation date of the latest plan request. This should be made available as a property on the plan object for reactabular to use, as part of processing the plan objects for display here: https://github.com/ManageIQ/manageiq-v2v/blob/master/app/javascript/react/screens/App/Overview/helpers.js#L7

**Comment by mturley** [comment]
@fdupont-redhat should this be made the new default sort for completed plans? I'm assuming we want it to start descending (latest executed plan first)

**Comment by fdupont-redhat** [comment]
I think it's a sane default. @vconzola what do you think ?

**Comment by mturley** [comment]
@vconzola to be specific about what we need here for `needs-design`:

* What should we call this field? "Date Migrated"? "Time Migrated?" "Migration Request Time"? It's not terribly intuitive to me how to name this. The technical definition of the column is "creation time of the latest migration request for the plan".
* Should this be only a new sort option at the top of the table, or should it also be a new column added to the table (not sure if there's enough room)?

**Comment by mturley** [comment]
Note to self: Fabien says we should sort by the last updated time here.
