### ISSUE TITLE
We should refactor our use of `UNSAFE_componentWillReceiveProps` to use safer patterns

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#935]
We renamed the usages of this method to include the `UNSAFE_` prefix in #890 to make our codebase safe for an upgrade to React 17+, but we should eventually move away from this deprecated method entirely to a more reasonable pattern (possibly using `componentWillUpdate` or `getDerivedStateFromProps` or memoization helpers).

See https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops for more info about why this method was deprecated and what to use instead.

**Comment by mturley** [comment]
Still should be done, but low priority.

**Comment by vconzola** [comment]
Close as wontfix - maybe someday.
