### ISSUE TITLE
PatternFly CSS Weirdness is showing up when running v2v with the latest master version of manageiq-ui-classic

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#959]
I'm not sure yet what's going on here, but it's not happening in `hammer` versions, so I'm not worrying about it for now. This will become a problem for the first CFME 5.11 builds though, so we should figure out what's going on.

I pulled the latest master of `manageiq-ui-classic` and restarted my dev environment, and I saw this in the plans list view:

![Screenshot 2019-05-22 16 24 52](https://user-images.githubusercontent.com/811963/58208665-2c8dee00-7cb3-11e9-9d29-aeae48b17bb2.png)

Something about the patternfly CSS has changed, it's messing with padding in our list view icons (and I notice the little clock icon next to the timestamps has changed). Opening this issue so we don't forget to address it.

**Comment by mturley** [comment]
This is related to conflicts with patternfly 4 and patternfly 3 CSS as is being discussed/addressed in https://github.com/ManageIQ/manageiq-ui-classic/pull/5622

**Comment by vconzola** [comment]
Not an issue anymore.
