### ISSUE TITLE
Configuring an OSP host without TLS certificate results in an infinite spinner

### ISSUE THREAD

**Issue by sshveta** [ManageIQ/manageiq-v2v#965]
Steps to Reproduce:
1. Add OSP and Vmware
2. From UI , configure OSP conversion host .
3. Do not provide value for TLS cert and configure .
4. Conversion host neither fails nor succeeds to add.
5. Infinite spinner

As in attached screenshot the spinner keeps spinning endlessly if the OSP conversion instance is configured without providing the TLS cert.
![Screenshot from 2019-05-29 18-06-32](https://user-images.githubusercontent.com/3866976/58606286-abed6580-824f-11e9-96d9-90c9fb08f3a3.png)

**Comment by sshveta** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1715266

**Comment by djberg96** [comment]
Anything in the logs to indicate where it's stuck?

**Comment by djberg96** [comment]
Also, running in debug mode should help get some ssh logging at least.

**Comment by sshveta** [comment]
Not able to recreate this issue on another appliance .Closing
