### ISSUE TITLE
[BZ#1694621] Completed migration plans search filter needs option to search plan with specified vm name

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#981]
Reported by YTale: https://bugzilla.redhat.com/show_bug.cgi?id=1694621

> When you have large numbers of plans on overview page, its hard to find in which plan you have your specified vm. Completed migration plans search filter needs option to search plan with specified vm name. Currently it is having filters like search by name/description/infra mapping, its will be nice to have vm name filter too which will return plan which have specified vm.

**Comment by mturley** [comment]
@vconzola I think we decided this isn't worth doing, but we never closed the BZ. Can you confirm that?

**Comment by vconzola** [comment]
@mturley It sounds like a useful feature if it's not too much work to implement. Let's talk about it tomorrow when we do backlog grooming...which I need to schedule.

**Comment by vconzola** [comment]
When fixing this it should apply to all plan views, not just completed plans.

**Comment by mturley** [comment]
BZ was closed as `wontfix`.
