### ISSUE TITLE
Migration Analytics #6 - Add Smart State Analysis status polling

### ISSUE THREAD

**Issue by mturley** [ManageIQ/manageiq-v2v#983]
This issue covers an additional readiness check during the polling before running the data extraction, that will scan for any pending smart state analysis tasks associated with the VMs in the selected providers, and wait for them to complete. The user will need some way of opting out of this potentially long waiting period if they don't care about smart state data.

**Comment by jerryk55** [comment]
@mturley is the assumption that you care about *all* VMs for the selected providers, or just a subset?

**Comment by mturley** [comment]
I'm assuming the user cares about all VMs, because we don't have a mocked up way of allowing the user to specify what VMs they care about for smart state data. If that's something we'll need, we'll have to adjust the design.

**Comment by mturley** [comment]
I know someone mentioned the user can tag certain VMs as being exempt from smart state, so I could check for those tags here and exclude those VMs from this check too. Although that might not be necessary, because I really just need the UI to wait for any in-progress smart state scans to complete, and excluded VMs will never have any in-progress scans.
