### ISSUE TITLE
Replace MiqSshUtil with nissh

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-v2v#991]
Just a placeholder issue for myself mostly. I want to replace our MiqSshUtil library from gems-pending with nissh, which is a nicer, better wrapper IMO. It also has a different philosophy regarding error handling, i.e. it doesn't raise exceptions, it's your job to check success and/or stderr.

The only thing holding me up is that per-session logging isn't supported. Well, it is in the repo, it just hasn't been released yet.

https://github.com/adamcooke/nissh

**Comment by mturley** [comment]
Hey @djberg96, is this still an issue? Is it v2v-related or should we move it to another repo?

**Comment by djberg96** [comment]
I think I'll close this since we're going to switch it to manageiq-ssh-util. I've started that here: https://github.com/ManageIQ/manageiq/pull/19843
